theme: jekyll-theme-cayman
title: Instant Automation
description: Automate everything in half the time
twitter_username: agazoth
github_username:  Agazoth
site-footer: "Investigate - Automate - Innovate"